[package]
name = "OmegaCode"
version = "0.1.0-alpha"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "OmegaCode"
path = "src/main.rs"

[dependencies]
clap = "4.6.1"
anyhow = "1.0.102"
tokio = { version = "1.52.3", features = ["full"] }
colored = "3.1.1"
indicatif = "0.18.4"
reqwest = "0.13.3"
tokio-stream = "0.1.18"
futures = "0.3.32"
futures-util = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
rmcp = "1.7.0"
rusqlite = { version = "0.39.0", features = ["bundled"] }
ratatui = "0.30.0"
crossterm = "0.29.0"
log = "0.4.29"
flexi_logger = "0.31.8"
chrono = "0.4.44"
rust-i18n = "4.0.0"
once_cell = "1.21.4"
ratatui-kit = { version = "0.5.9", features = ["full"] }
